### ISSUE TITLE
Receiving a message for a non existent session breaks the SIP stack

### ISSUE THREAD

**Issue by cwysong85** [cwysong85/sipjs-udp#4]
To recreate, just send a notify to the stack after starting it. 

```
 Mon Apr 01 2019 14:21:02 GMT+0000 (Coordinated Universal Time) | sip.ua | received NOTIFY request for a non existent session
 /app/text-translation-sip-bot/node_modules/sipjs-udp/src/SIPMessage.js:481
   this.server_transaction.receiveResponse(code, response).then(onSuccess, onFailure);
                           ^
 
 TypeError: Cannot read property 'receiveResponse' of null
     at IncomingRequest.reply (/app/text-translation-sip-bot/node_modules/sipjs-udp/src/SIPMessage.js:481:27)
     at UA.receiveRequest (/app/text-translation-sip-bot/node_modules/sipjs-udp/src/UA.js:627:29)
     at Transport.onMessage (/app/text-translation-sip-bot/node_modules/sipjs-udp/src/Transport.js:140:29)
     at Socket.<anonymous> (/app/text-translation-sip-bot/node_modules/sipjs-udp/src/Transport.js:85:27)
     at Socket.emit (events.js:197:13)
     at UDP.onMessage [as onmessage] (dgram.js:685:8)
```

**Comment by cwysong85** [comment]
Turns out sending an INVITE with an existing To tag header breaks the SIPMessage.js file. I'm able to recreate this with SIPP and the scenario file called "invite-with-existing-to-tag.xml"

**Comment by cwysong85** [comment]
This is now fixed in branch `issue-4`. Ended up that we needed to check if the transaction didn't exist, we needed to create it and allow the stack to reply normally. To run the test, `sipp -sf test/invite-with-existing-to-tag.xml -i 127.0.0.1 -p 5065 -m 1 127.0.0.1:5060`
